[versions]
agp = "9.4.0"
arcore = "1.56.0"
junit = "4.13.2"

[libraries]
arcore = { group = "com.google.ar", name = "core", version.ref = "arcore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
